# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190404_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='env',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
