# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20190405_0927'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='envconfigparams',
            unique_together=set([('Env', 'key')]),
        ),
        migrations.AlterUniqueTogether(
            name='micserviceconfigparams',
            unique_together=set([('MicService', 'Env', 'key')]),
        ),
    ]
